name: Build AAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make Gradle Wrapper executable
      run: chmod +x gradlew

    - name: Build AAR
      run: ./gradlew :library:assembleRelease

      
    - name: Upload AAR
      uses: actions/upload-artifact@v4
      with:
        name: library-aar
        path: library/build/outputs/aar/*.aar
